
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: devops-test-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/devops-test-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Password1